### get client almuali699@gmail.com

GET http://localhost:3002/customer/almuali699@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5NDU5ODA5LCJleHAiOjE2MDk0NTk4Njl9.sxywh8J_VQ2gJiYQ9A9xpZ-4VKbdObKpz4yv2eSJoz0

### get list of all merchants
GET http://localhost:3002/merchant/

### pay a bill
POST http://localhost:3002/merchant/RBC%20Visa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5NDc1NDc1LCJleHAiOjE2MDk0NzU1MzV9.ZoS8fBeMigorCxsUIAwrJxNZUCFku20jcTt-0NYkb6o
Content-Type: application/json

{
    "accountNumber": "1111222233334444",
    "amount": 20
}

### transfer
POST http://localhost:3002/customer/amusawi3@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5NDc3NTkxLCJleHAiOjE2MDk0Nzc2NTF9.Rkac5YZ0tMR1VcuMGeB98qJpwMe8rdAHzi3AHh7Qp3g
Content-Type: application/json

{
    "accountNumber": "1111222233334444",
    "amount": 100
}

